version: '3.8'

services:
  certbot:
    build:
      context: .
      dockerfile: ../Dockerfile
    container_name: certbot-stackit
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./stackit.ini:/stackit.ini:ro
    entrypoint: certbot
    command: >
      certonly
      --agree-tos
      --non-interactive
      --email dns@${DOMAIN}
      --authenticator dns-stackit
      --dns-stackit-credentials /stackit.ini
      --dns-stackit-propagation-seconds 60
      -d "${WILDCARD}" -d "${DOMAIN}"
  certbot-renew:
    build:
      context: .
      dockerfile: ../Dockerfile
    container_name: certbot-renew
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./stackit.ini:/stackit.ini:ro
    entrypoint: certbot
    command: renew